### PR TITLE
Add vdw_kernels make target

### PR DESCRIPTION
**Pull request by afonari**
To generate kernels for vdW functionals

### CODE REVIEW

**Comment by afonari** [comment]
Seems to work fine, from the Travis CI make output:
```
make[2]: Leaving directory `/home/travis/build/QEF/q-e_schrodinger/PW/tools'
make[1]: Leaving directory `/home/travis/build/QEF/q-e_schrodinger/PW'
bin/generate_vdW_kernel_table.x
bin/generate_rVV10_kernel_table.x
```

**Review by giannozz — COMMENTED** [review]
It adds a significant overhead at every compilation (or doesn't it?)

**Comment by afonari** [comment]
If the make target is 'pwall' or 'all', than yes. I could remove 'vdw_kernels' target from pwall and all, to make it completely optional.

**Comment by afonari** [comment]
Made 'vdw_kernels' target completely optional.

**Comment by fspiga** [comment]
I imagine there is a reason to have "rVV10_kernel_table" and "vdW_kernel_table" in the $ESPRESSO_ROOT. Merged.

**Comment by afonari** [comment]
Thanks Filippo!

**Pull request merged**
