### PR TITLE
Fix crash due to superfluous WRITE argument

### PR DESCRIPTION
**Pull request by afonari**

### CODE REVIEW

**Comment by pietrodelugas** [comment]
are we sure we should not include instead a forgotten format string for 
the integer

nrot as a few lines above ?

**Comment by afonari** [comment]
Update to print nrot. Also attaching files to reproduce the CRASH/fix.

[Archive.tar.gz](https://github.com/QEF/q-e_schrodinger/files/742475/Archive.tar.gz)

**Comment by pietrodelugas** [comment]
yes but then we should add again nrot argument :).

Anyway as I am building an xml element reporting warnings and info 
messages,  it would be useful that the printous was done calling  
info_msg here as above.

Sorry for the interference, Sasha :(.

**Comment by afonari** [comment]
Np Pietro, fixed.

**Review by fspiga — APPROVED** [review]

**Comment by fspiga** [comment]
SVN will reflect as well this last change

**Pull request merged**
