### PR TITLE
Updating q-e_schrodinger distribution to QE Bundle 2.0

### PR DESCRIPTION
**Pull request by fspiga**

### CODE REVIEW

**Comment by fspiga** [comment]
Alignment with QE v6.1 (+minor fixes), "QE Bundle 2.0" includes PHonon and TDDFPT. Various makefiles still to be fixed

**Comment by afonari** [comment]
Currently (in the qe_schrodinger/master) there is no docs/examples?

**Comment by fspiga** [comment]
Yes, there is something but scattered in various sub directories. it is possible to update everything. Removing docs and examples, if not used, will make the overall final package lighter.

**Comment by afonari** [comment]
Let's update everything, I think the distribution is still reasonable (< 50MB)

**Comment by fspiga** [comment]
Done. I am happy to rebase this branch into master if everyone is happy. I wait Paolo and/or Pietro review before act.

**Comment by afonari** [comment]
Looks good! Thanks!

**Review by pietrodelugas — APPROVED** [review]
this commit is an alignment of the repository  to the qe trunk, it is well tested.

**Comment by giannozz** [comment]
The patch is too big to be reviewed, but I do not foresee any problems

**Pull request merged**
